import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <style
          dangerouslySetInnerHTML={{
            __html: `
          .theme-init {
            transition: none !important;
            opacity: 0 !important;
          }
          html:not(.theme-init) {
            opacity: 1;
            transition: opacity 0.3s ease;
          }
        `,
          }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
          document.documentElement.classList.add('theme-init');
          try {
            if (localStorage.getItem('theme') === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
              document.documentElement.classList.add('dark');
            } else {
              document.documentElement.classList.remove('dark');
            }
            setTimeout(function() {
              document.documentElement.classList.remove('theme-init');
            }, 10);
          } catch (e) {}
        `,
          }}
        />
      </head>
      <body className={`${poppins.variable} antialiased font-poppins`}>
        {children}
      </body>
    </html>
  );
}
